### PR TITLE
Initiate website

### PR DESCRIPTION
**Pull request by ayushjn20**
Template: https://www.gatsbyjs.org/starters/hasura/gatsby-gitbook-starter/

### CODE REVIEW

**Comment by agentmilindu** [comment]
Screenshot from 2019-07-24 00-57-03

**Comment by agentmilindu** [comment]
Screenshot from 2019-07-24 01-01-27

:tada:

**Comment by agentmilindu** [comment]
Screenshot from 2019-07-24 01-05-09

**Review by tdevinda — APPROVED** [review]
Looks good. Maybe we can add some block diagram type images later on. But this is more than enough for starting up.

**Review by rajikaimal — APPROVED** [review]

**Pull request merged**
